
[project]
name = "claude-ops"
version = "2.0.0"
description = "Telegram-Claude Bridge System for development workflow automation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.0",
    "python-telegram-bot>=20.0",
    "requests>=2.25.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
]
