
[project]
name = "claude-ops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "notion-client>=2.4.0",
    "pandas>=2.3.1",
    "pygithub>=2.6.1",
    "python-dotenv>=1.0.0",
    "python-telegram-bot>=20.0",
    "scikit-learn>=1.7.1",
]
